import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthProvider from "./authProvider";
import { GlobalProvider } from "@/context/GlobalContext";
import { ReactQueryClientProvider } from "./ReactQueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <ReactQueryClientProvider>
            <GlobalProvider>
              <Navbar />
              {children}
              <Footer />
            </GlobalProvider>
          </ReactQueryClientProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
